config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root 'top#index'

  resources :address, only: [:show, :edit, :update, :destroy]
  resources :users, only: [:show, :edit, :update, :destroy] do
    collection do
      get 'profile', to: 'users#profile'
      get 'overview', to: 'users#overview'
      get 'problem', to: 'users#problem'
    end
  end

  resources :items, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'season', to: 'items#season'
      get 'color', to: 'items#color'
      get 'brand', to: 'items#brand'
    end
    collection do # 新規用（new) usr:items/newのため
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
      get 'category_size', defaults: { format: 'json' }
    end
    member do # 編集(edit用) usl: items/id/editのため
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
      get 'category_size', defaults: { format: 'json' }
    end
    resources :categories, only: [:show]
  end
  
  resources :coordinates do
    collection do
      get 'history', to: 'coordinates#history'
    end
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resources :bookmarks, only: [:index, :create, :destroy]
  end
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :coordinate, counter_cache: :bookmarks_count

  validates :user_id, presence: true
  validates :coordinate_id, presence: true
  validates_uniqueness_of :coordinate_id, scope: :user_id
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_coordinate, only: [:create, :destroy]

  def index
    @bookmark = Bookmark.new
    @bookmarks = Bookmark.includes(:coordinate, coordinate: :user).order(created_at: "DESC").page(params[:page]).per(6)
  end

  def create
    @bookmark = Bookmark.create(user_id: current_user.id, coordinate_id: params[:coordinate_id])
    @bookmarks = Bookmark.where(coordinate_id: params[:coordinate_id])
    @coordinate.reload
  end

  def destroy
    @bookmark = Bookmark.find_by(user_id: current_user.id, coordinate_id: params[:coordinate_id])
    @bookmark.destroy
    @bookmarks = Bookmark.where(coordinate_id: params[:coordinate_id])
    @coordinate.reload
  end
  
  private

  def set_coordinate
    @coordinate = Coordinate.find(params[:coordinate_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:coordinate_id, :user_id).merge(user_id: current_user.id)
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/_bookmark.html.erb
<div class="contents__coordinate__show__left__like__okini">
  <% if user_signed_in? %>
    <% if @coordinate.bookmark_user(current_user.id) %>
      <%= link_to coordinate_bookmark_path(current_user, @bookmark, coordinate_id: @coordinate.id), method: "DELETE", class:"contents__coordinate__show__left__like__okini__bookmark", id: "bookmark-button", remote:true do %>
        <%# <i class="fa fa-heart like-btn" ></i> %>
        <div class="contents__coordinate__show__left__like__okini__bookmark__mark" >お気に入り</div>
        <span class="contents__coordinate__show__left__like__okini__bookmark__count">
          <%= @bookmarks.where(coordinate_id: @coordinate.id).count %>
        </span>
      <% end %>
    <% else %>
      <%= link_to coordinate_bookmarks_path(current_user, coordinate_id: @coordinate.id), method: "POST", class:"contents__coordinate__show__left__like__okini__bookmark", id: "bookmark-button", remote:true do %>
        <div class="contents__coordinate__show__left__like__okini__bookmark__mark" >お気に入り</div>
        <span class="contents__coordinate__show__left__like__okini__bookmark__count">
          <%= @bookmarks.where(coordinate_id: @coordinate.id).count %>
        </span>
      <% end %>
    <% end %>
  <% else %>
    <div class="contents__coordinate__show__left__like__okini__bookmark">
      <div class="contents__coordinate__show__left__like__okini__bookmark__mark" >お気に入り</div>
      <span class="contents__coordinate__show__left__like__okini__bookmark__count">
        <%= @bookmarks.where(coordinate_id: @coordinate.id).count %>
      </span>
    </div>
  <% end %>
</div>

app/views/bookmarks/_borad.html.erb
<div class="content__mypage__right__borad__list">
  <div class="content__mypage__right__borad__list__image">
    <% if bookmark.coordinate.image.present? %>
      <%= link_to image_tag("#{bookmark.coordinate.image }", height: "280px"), coordinate_path(bookmark.coordinate.id) %>
    <% else %>
      <%= link_to image_tag("/Unknown.png", height: "280px"), coordinate_path(bookmark.coordinate.id) %>
    <% end %>
    <div class="content__mypage__right__borad__list__image__time">
      <%= bookmark.coordinate.created_at.strftime('%Y/%m/%d') %>
    </div>
  </div>
  <div class="content__mypage__right__borad__list__middle">
    <div class="content__mypage__right__borad__list__middle__okini">
      <%= link_to "お気に入り", coordinate_path(bookmark.coordinate.id), class: "content__mypage__right__borad__list__middle__okini" %>
      <%= Bookmark.where(coordinate_id: bookmark.coordinate[:id]).count %>
    </div> 
    <div class="content__mypage__right__borad__list__middle__like">
      <%= link_to image_tag('/iconmonstr-heart-thin.png', height:'15px', width:'15px'), coordinate_path(bookmark.coordinate.id) %>
      <%= Like.where(coordinate_id: bookmark.coordinate[:id]).count %>
    </div>
  </div>
  <div class="content__mypage__right__borad__list__low">
    <span>ユーザーネーム：</span>
    <%= link_to bookmark.coordinate.user.nickname, coordinate_path(bookmark.coordinate.id), class: "content__mypage__right__borad__list__low__nickname" %>
    <div class="content__mypage__right__borad__list__low__height">
      <%= bookmark.coordinate.height.name %>
    </div>
  </div>
</div>

app/views/bookmarks/create.js.erb
$("#bookmark-button").html("<%= j(render partial: 'bookmarks/bookmark', locals: { coordinate: @coordinate, coordinates: @coordinates, bookmarks: @bookmarks, bookmark: @bookmark}) %>");

app/views/bookmarks/destroy.js.erb
$("#bookmark-button").html("<%= j(render partial: 'bookmarks/bookmark', locals: { coordinate: @coordinate, coordinates: @coordinates, bookmarks: @bookmarks, bookmark: @bookmark }) %>");

app/views/bookmarks/index.html.erb
<header>
  <div class ="pcHeader">
    <div class="pcHeader__headerInner">
      <div class="pcHeader__headerInner__mainHeader">
        <div class="pcHeader__headerInner__mainHeader__title">
          <%= link_to "Fashion Book", '/', class: "pcHeader__headerInner__mainHeader__title__main" %>
          <div class="pcHeader__headerInner__mainHeader__title__sub">毎日の服選びをおしゃれで楽に</div>
        </div>
      </div>
    </div>
  </div>
</header>
<% breadcrumb :bookmark %>
<%= breadcrumbs separator: " &rsaquo; " %>
<div class="contents">
  <div class="content">
    <div class="content__mypage">
      <div class="content__mypage__left">
        <ul class="content__mypage__left__side">
          <li class="content__mypage__left__side__list">
            <%= link_to 'マイページ', user_path(current_user.id), class: "content__mypage__left__side__list__menu" %>
            <ul>
              <li>
                <%= link_to '#', class: "content__mypage__left__side__list__menu__tag" do %>
                  コーディネート選択<%= fa_icon("angle-right") %>
                <% end %>
              </li>
              <li>
                <%= link_to coordinates_path, class: "content__mypage__left__side__list__menu__tag" do %>
                  コーディネート一覧<%= fa_icon("angle-right") %>
                <% end %>
              </li>
              <li>
                <%= link_to coordinate_bookmarks_path, class: "content__mypage__left__side__list__menu__tag" do %>
                  お気に入り一覧<%= fa_icon("angle-right") %>
                <% end %>
              </li>
              <li>
                <%= link_to items_path, class: "content__mypage__left__side__list__menu__tag" do %>
                  アイテム一覧<%= fa_icon("angle-right") %>
                <% end %>
              </li>
              <li>
                <%= link_to history_coordinates_path(@coordinate), method: :GET, class: "content__mypage__left__side__list__menu__tag" do %>
                  閲覧履歴<%= fa_icon("angle-right") %>
                <% end %>
              </li>
            </ul>
          </li>
        </ul>
      </div>
      <div class="content__mypage__right">
        <div class="content__mypage__right__seach">
          <h2>お気に入り一覧</h2>
        </div>
        <div class="content__mypage__right__borad">
          <% @bookmarks.each do |bookmark| %>
            <% if user_signed_in? && current_user.id == bookmark.user_id %>
              <%= render partial: "borad", locals: { coordinate: @coordinate, coordinates: @coordinates, bookmark: bookmark, bookmarks: @bookmarks } %>
            <% else %>
              <div class="contents__coordinate__index__right__borad__no">お気に入りに追加したコーディネートはありません</div>
            <% end %> 
          <% end %>
          <%= paginate(@bookmarks) %>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render partial: 'top/footer' %>