config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root 'top#index'

  resources :address, only: [:show, :edit, :update, :destroy]
  resources :users, only: [:show, :edit, :update, :destroy] do
    collection do
      get 'profile', to: 'users#profile'
      get 'overview', to: 'users#overview'
      get 'problem', to: 'users#problem'
    end
  end

  resources :items, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'season', to: 'items#season'
      get 'color', to: 'items#color'
      get 'brand', to: 'items#brand'
    end
    collection do # 新規用（new) usr:items/newのため
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
      get 'category_size', defaults: { format: 'json' }
    end
    member do # 編集(edit用) usl: items/id/editのため
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
      get 'category_size', defaults: { format: 'json' }
    end
    resources :categories, only: [:show]
  end
  
  resources :coordinates do
    collection do
      get 'history', to: 'coordinates#history'
    end
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resources :bookmarks, only: [:index, :create, :destroy]
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index
    @parents = Category.where(ancestry: nil)
  end
  
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/top/_footer.html.erb
<footer>
  <div class = "pcFooter">
    <div class = "pcFooter__footer">
      <div class = "pcFooter__footer__content">
        <div class = "pcFooter__footer__content__left">
          <ul>
            <li><%= link_to "作成者概要", profile_users_path, class: "pcFooter__footer__content__left__list" %></li>
            <li><%= link_to "制作概要", overview_users_path, class: "pcFooter__footer__content__left__list" %></li>
            <li><%= link_to "実装機能・課題", problem_users_path, class: "pcFooter__footer__content__left__list" %></li>
          </ul>
        </div>
        <div class = "pcFooter__footer__content__center">
          <ul>
            <li><%= link_to "コーディネート一覧", coordinates_path, class: "pcFooter__footer__content__center__list" %></li>
            <li><%= link_to "ユーザー一覧", '#', class: "pcFooter__footer__content__center__list" %></li>
            <li><%= link_to "アイテム一覧", items_path, class: "pcFooter__footer__content__center__list" %></li>
            <li><%= link_to "ブランド一覧", '#', class: "pcFooter__footer__content__center__list" %></li>
            <li><%= link_to "カテゴリー一覧", '#', class: "pcFooter__footer__content__center__list" %></li>
          </ul>
        </div>
        <div class = "pcFooter__footer__content__right">
          <ul>
            <li><%= link_to "コーディネートランキング", '#', class: "pcFooter__footer__content__right__list" %></li>
            <li><%= link_to "ユーザーランキング", '#', class: "pcFooter__footer__content__right__list" %></li>
            <li><%= link_to "トレンドキーワード", '#', class: "pcFooter__footer__content__right__list" %></li>
            <li><%= link_to "髪型別コーデ検索", '#', class: "pcFooter__footer__content__right__list" %></li>
          </ul>
        </div>
      </div>
    </div>
    <div class = "pcFooter__footerLogo">
      服は人を変えられる
      <%# <%= link_to "お知らせ", '#' %>
      <%# %a(href="#") %>
        <%# = image_tag 'logo-white.png', height: '100%', width: '100%', alt: 'logo' %>
    </div>
    <p>© Fashion Book</p>
  </div>
</footer>

app/views/top/index.html.erb
<header>
  <div class ="pcHeader">
    <div class="pcHeader__headerInner">
      <div class="pcHeader__headerInner__mainHeader">
        <div class="pcHeader__headerInner__mainHeader__title">
          <%= link_to "Fashion Book", '/', class: "pcHeader__headerInner__mainHeader__title__main" %>
          <div class="pcHeader__headerInner__mainHeader__title__sub">毎日の服選びをおしゃれで楽に</div>
        </div>
        <%# %a(href="/")
          = image_tag 'logo.png', height: '40px', width: '150px', alt: 'icon', class: 'pcHeader__headerInner__mainHeader__app'
        .pcHeader__headerInner__mainHeader__searchBox
          = text_field_tag '', '', placeholder: 'キーワードから探す', class: 'pcHeader__headerInner__mainHeader__searchBox__box'
          .pcHeader__headerInner__mainHeader__searchBox__btn
            %a(href="#")
              = image_tag 'icon-search 1.png', height: '100%', width: '100%', alt: 'search' %>
      </div>
      <div class="pcHeader__headerInner__nav">
        <ul class = "pcHeader__headerInner__nav__listLeft">
          <li class = "pcHeader__headerInner__nav__listLeft__first">
            <%= link_to "#" do %> 
              カテゴリー
            <% end%>
            <ul class = "pcHeader__headerInner__nav__listLeft__first__parents">
              <% @parents.each do |parent| %> 
              <%# 親カテゴリの中身 %>
                <li class = "pcHeader__headerInner__nav__listLeft__first__parents__parent">
                  <%= link_to "#" do%> 
                    <%= parent.name %> 
                  <% end %>
                  <%# 子カテゴリの大枠 %>
                  <ul class = "pcHeader__headerInner__nav__listLeft__first__parents__parent__children">
                    <% parent.children.each do |child| %> 
                      <%# 子カテゴリの中身 %>
                      <li class = "pcHeader__headerInner__nav__listLeft__first__parents__parent__children__child">
                        <%= link_to "#" do %> 
                          <%= child.name %> 
                        <% end %>
                        <%# 孫カテゴリの大枠 %>
                        <ul class = "pcHeader__headerInner__nav__listLeft__first__parents__parent__children__child__grandchildren">
                          <% child.children.each do |grandchild| %> 
                            <%# 孫カテゴリの中身 %>
                            <li class = "pcHeader__headerInner__nav__listLeft__first__parents__parent__children__child__grandchildren__grandchild">
                              <%= link_to "#" do %> 
                                <%= grandchild.name %> 
                              <% end %>
                            </li>
                          <% end %>
                        </ul>
                      </li>
                    <% end %>
                  </ul>
                </li>
              <% end %>
            </ul>
          </li>
        </ul>
        <%= link_to "ブランド", '#', class:"pcHeader__headerInner__nav__listLeft__item" %>
        <div class = "pcHeader__headerInner__nav__listRight">
          <% if user_signed_in? && current_user.id %>
            <%= link_to "マイページ", user_path(current_user), class:"pcHeader__headerInner__nav__listRight"%>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "ログイン", new_user_session_path, class:"pcHeader__headerInner__nav__listLeft__first" %>
            <%= link_to "新規会員登録", new_user_registration_path, class:"pcHeader__headerInner__nav__listLeft__item" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</header>

<div class="contents">
  <div class="content">
    <div class="content__main">
      <div class="content__main__left">
        <ul class="content__main__left__side">
          <li class="content__main__left__side__list">
            <h2 class="content__main__left__side__list__menu">探す</h2>
            <ul>
              <li><%= link_to "コーディネートを探す", '#', class: "content__main__left__side__list__menu__list" %></li>
              <li><%= link_to "ユーザーを探す", '#', class: "content__main__left__side__list__menu__list" %></li>
              <li><%= link_to "アイテムを探す", '#', class: "content__main__left__side__list__menu__list" %></li>
              <li><%= link_to "ブランドを探す", '#', class: "content__main__left__side__list__menu__list" %></li>
            </ul>
            <h2 class="content__main__left__side__list__menu">投稿一覧</h2>
            <ul>
              <li><%= link_to "ALL", '#', class: "content__main__left__side__list__menu__list" %></li>
              <li><%= link_to "MEN", '#', class: "content__main__left__side__list__menu__list" %></li>
              <li><%= link_to "WOMEN", '#', class: "content__main__left__side__list__menu__list" %></li>
              <li><%= link_to "KIDS", '#', class: "content__main__left__side__list__menu__list" %></li>
            </ul>
            <h2 class="content__main__left__side__list__menu">SNS</h2>
            <ul>
              <li><a class="fa fa-github" href="https://github.com/takahiro-ueda">　GitHub</a></li>
              <li><a a class="fa fa-twitter" href="https://twitter.com/home">　Twitter</a></li>
              <li><a a class="fa fa-wikipedia-w" href="https://www.wantedly.com/users/135157931">　Wantedly</a></li>
            </ul>
          </li>
        </ul>
      </div>
      <div class="content__main__right">
        <div class="content__main__right__seach">
        </div>
      </div>
    </div>
  </div>
</div>

<%= render partial: 'footer' %>

<%# if user_signed_in?
  = link_to new_item_path, class: "purchaseBtn" do
    .purchaseBtn
      %span 出品する
      .purchaseBtn__icon
        = image_tag 'icon_camera.png', height: '100%', width: '100%', alt: 'logo'
- else
  = link_to new_user_session_path,class: "purchaseBtn" do
    .purchaseBtn
      %span 出品する
      %span.note ※ログインが必要です
      .purchaseBtn__icon
        = image_tag 'icon_camera.png', height: '100%', width: '100%', alt: 'logo' %>