config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root 'top#index'

  resources :address, only: [:show, :edit, :update, :destroy]
  resources :users, only: [:show, :edit, :update, :destroy] do
    collection do
      get 'profile', to: 'users#profile'
      get 'overview', to: 'users#overview'
      get 'problem', to: 'users#problem'
    end
  end

  resources :items, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'season', to: 'items#season'
      get 'color', to: 'items#color'
      get 'brand', to: 'items#brand'
    end
    collection do # 新規用（new) usr:items/newのため
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
      get 'category_size', defaults: { format: 'json' }
    end
    member do # 編集(edit用) usl: items/id/editのため
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
      get 'category_size', defaults: { format: 'json' }
    end
    resources :categories, only: [:show]
  end
  
  resources :coordinates do
    collection do
      get 'history', to: 'coordinates#history'
    end
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resources :bookmarks, only: [:index, :create, :destroy]
  end
end

app/models/coordinate.rb
class Coordinate < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :gender
  belongs_to_active_hash :height
  belongs_to_active_hash :age
  belongs_to_active_hash :month
  belongs_to_active_hash :hairstyle

  belongs_to :user, optional: true
  has_many :items
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_users, through: :bookmarks, source: :user
  def bookmark_user(user_id)
    bookmarks.find_by(user_id: user_id)
  end

  has_many :browsing_histories, dependent: :destroy
  has_many :history_users, through: :browsing_histories, source: :user

  mount_uploader :image, ImageUploader
  validates :name,
    length: { maximum:50, message: "入力は５０文字までです。"}
  validates :introduction,
    length: { maximum:2000, message: "入力は２０００文字までです。"}
end

app/controllers/coordinates_controller.rb
class CoordinatesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :history]
  before_action :set_coordinate, except: [:index, :new, :create]
  before_action :set_coordinate, only: [:show, :destroy, :edit, :update]
  before_action :move_to_index, except: [:index, :show, :history]

  def index
    @coordinate = Coordinate.new
    @coordinates = Coordinate.includes(:user).order(created_at: "DESC").page(params[:page]).per(9)
    @likes = Like.where(user_id: current_user)
    @bookmarks = Bookmark.where(user_id: current_user)
  end

  def new
    @coordinate = Coordinate.new
  end

  def create
    @coordinate = Coordinate.new(coordinate_params)
    if user_signed_in?
      @coordinate.user_id = current_user.id
    end
    unless @coordinate.valid?
      flash.now[:alert] = @coordinate.errors.full_messages
      @coordinate.image
      render :new and return
    end
    if @coordinate.save
      redirect_to coordinates_path(id: current_user)
    else
      render :new
    end
  end

  def edit
  end

  def update
    unless @coordinate.valid?
      flash.now[:alert] = @coordinate.errors.full_messages
      render :edit and return
    end
    if @coordinate.update(coordinate_params)
      redirect_to coordinates_path
    else
      render :edit and return
    end
  end

  def show
    @gender = @coordinate.gender
    @height = @coordinate.height
    @age = @coordinate.age
    @month = @coordinate.month
    @hairstyle = @coordinate.hairstyle
    @comment = Comment.new
    #新着順で表示
    @comments = @coordinate.comments.includes(:user).order(created_at: :desc)
    @like = 0
    @likes = Like.where(coordinate_id: params[:id])
    @bookmark = 0
    @bookmarks = Bookmark.where(coordinate_id: params[:id])

    new_history = @coordinate.browsing_histories.new
    new_history.user_id = current_user.id
    if current_user.browsing_histories.exists?(coordinate_id: "#{params[:id]}")
      old_history = current_user.browsing_histories.find_by(coordinate_id: "#{params[:id]}")
      old_history.destroy
    end
    new_history.save
    histories_stock_limit = 9
    histories = current_user.browsing_histories.all
    if histories.count > histories_stock_limit
      histories[0].destroy
    end
  end

  def destroy
    if @coordinate.destroy
      redirect_to coordinates_path, notice: '削除に成功しました。'
    else
      flash.now[:alert] = '削除に失敗しました。'
      render :edit
    end
  end

  def history
    @histories = BrowsingHistory.includes(:coordinate, coordinate: :user).order(created_at: "DESC")
    @coordinate = Coordinate.all
  end

  private

  def coordinate_params
    params.require(:coordinate).permit(
      :image, 
      :name,
      :introduction, 
      :gender_id,
      :height_id,
      :age_id,
      :month_id,
      :hairstyle_id, 
      ).merge(user_id: current_user.id)
  end

  def set_coordinate
    @coordinate = Coordinate.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/helpers/coordinates_helper.rb
module CoordinatesHelper
end

app/views/coordinates/_coordinate.html.erb
<div class="contents__coordinate__index__right__list__tag">
  <div class="contents__coordinate__index__right__list__tag__image">
    <% if coordinate.image.present? %>
      <%= link_to image_tag("#{coordinate.image }", height: "280px"), coordinate_path(coordinate.id) %>
    <% else %>
      <%= link_to image_tag("/Unknown.png", height: "280px"), coordinate_path(coordinate.id) %>
    <% end %>
    <div class="contents__coordinate__index__right__list__tag__image__time">
      <%= coordinate.created_at.strftime('%Y/%m/%d') %>
    </div>
  </div>
  <div class="contents__coordinate__index__right__list__tag__middle">
    <div class="contents__coordinate__index__right__list__tag__middle__okini">
      <%= link_to "お気に入り", coordinate_path(coordinate.id), class: "contents__coordinate__index__right__list__tag__middle__okini" %>
      <%= Bookmark.where(coordinate_id: coordinate[:id]).count %>
    </div> 
    <div class="contents__coordinate__index__right__list__tag__middle__like">
      <%= link_to image_tag('/iconmonstr-heart-thin.png', height:'15px', width:'15px'), coordinate_path(coordinate.id) %>
      <%= Like.where(coordinate_id: coordinate[:id]).count %>
    </div>
  </div>
  <div class="contents__coordinate__index__right__list__tag__low">
    <span>ユーザーネーム：</span>
    <%= link_to coordinate.user.nickname, coordinate_path(coordinate.id), class: "contents__coordinate__index__right__list__tag__low__nickname" %>
    <div class="contents__coordinate__index__right__list__tag__low__height">
      <%= coordinate.height.name %>
    </div>
  </div>
</div>

app/views/coordinates/_history.html.erb
<div class="content__mypage__right__history__list">
  <div class="content__mypage__right__history__list__image">
    <% if history.coordinate.image.present? %>
      <%= link_to image_tag("#{history.coordinate.image }", height: "280px"), coordinate_path(history.coordinate.id) %>
    <% else %>
      <%= link_to image_tag("/Unknown.png", height: "280px"), coordinate_path(history.coordinate.id) %>
    <% end %>
    <div class="content__mypage__right__history__list__image__time">
      <%= history.coordinate.created_at.strftime('%Y/%m/%d') %>
    </div>
  </div>
  <div class="content__mypage__right__history__list__middle">
    <div class="content__mypage__right__history__list__middle__okini">
      <%= link_to "お気に入り", coordinate_path(history.coordinate.id), class: "content__mypage__right__history__list__middle__okini" %>
      <%= Bookmark.where(coordinate_id: history.coordinate[:id]).count %>
    </div> 
    <div class="content__mypage__right__history__list__middle__like">
      <%= link_to image_tag('/iconmonstr-heart-thin.png', height:'15px', width:'15px'), coordinate_path(history.coordinate.id) %>
      <%= Like.where(coordinate_id: history.coordinate[:id]).count %>
    </div>
  </div>
  <div class="content__mypage__right__history__list__low">
    <span>ユーザーネーム：</span>
    <%= link_to history.coordinate.user.nickname, coordinate_path(history.coordinate.id), class: "content__mypage__right__history__list__low__nickname" %>
    <div class="content__mypage__right__history__list__low__height">
      <%= history.coordinate.height.name %>
    </div>
  </div>
</div>

app/views/coordinates/edit.html.erb
<header>
  <div class ="header">
    <div class="header__item">
      <div class="header__item__show">
        <div class="header__item__show__title">
          <%= link_to "Fashion Book", '/', class: "header__item__show__title__main" %>
          <div class="header__item__show__title__sub">毎日の服選びをおしゃれで楽に</div>
        </div>
        <div class = "header__item__show__lists">
          <% if user_signed_in? && current_user.id == @coordinate.user_id %>
            <div class="header__item__show__lists__list">
              <%= link_to '戻る', coordinate_path(@coordinate.id), class: "header__item__show__lists__list__back" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</header>
<% breadcrumb :edit_coordinate %>
<%= breadcrumbs separator: " &rsaquo; " %>
<div class="contents">
  <div class="contents__coordinate">
    <div class="contents__coordinate__title">
      <h2>コーディネート編集</h2>
    </div>
    <div class="contents__coordinate__edit">
    <%= form_with(model: @coordinate, class: :form, local: true) do |form| %>
      <% if @coordinate.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@coordinate.errors.count, "件のエラーにより") %> この投稿は保存できませんでした。</h2>
          <ul>
            <% @coordinate.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    
      <div class="contents__coordinate__edit__image">
        <%= form.label :image, 'コーディネート画像(画像をもう一度選択してください)' %>
        <%= form.file_field :image, class: :contents__coordinate__edit__image__select, id: "image-form" %>
        <div id="file"></div>
      </div>

      <div class="contents__coordinate__edit__name">
        <%= form.label :name, 'コーディネート名' %>
        <%= form.text_area :name, placeholder: :コーディネート名50文字まで, class: :form__name2 %>
      </div>

      <div class="contents__coordinate__edit__introduction">
        <%= form.label :introduction, 'コーディネート詳細' %>
        <%= form.text_area :introduction, placeholder: :'コーディネート紹介文(2000文字以内)', class: 'form__introduction2 js-text' %>
        <P class="js_text_count"></P>
      </div>

      <div class="contents__coordinate__edit__gender">
        <%= form.label :gender_id, '性別' %>
        <%= form.collection_select :gender_id, Gender.all, :id, :name, {prompt: "選択してください"}, {class: "form__gender"} %>
      </div>

      <div class="contents__coordinate__edit__height">
        <%= form.label :height_id, '身長' %>
        <%= form.collection_select :height_id, Height.all, :id, :name, {prompt: "選択してください"}, {class: "form__height"} %>
      </div>

      <div class="contents__coordinate__edit__age">
        <%= form.label :age_id, '年齢' %>
        <%= form.collection_select :age_id, Age.all, :id, :name, {prompt: "選択してください"}, {class: "form__age"} %>
      </div>

      <div class="contents__coordinate__edit__month">
        <%= form.label :month_id, '投稿月' %>
        <%= form.collection_select :month_id, Month.all, :id, :name, {prompt: "選択してください"}, {class: "form__month"} %>
      </div>

      <div class="contents__coordinate__edit__hairstyle">
        <%= form.label :hairstyle_id, '髪型' %>
        <%= form.collection_select :hairstyle_id, Hairstyle.all, :id, :name, {prompt: "選択してください"}, {class: "form__hairstyle"} %>
      </div>

      <div class="contents__coordinate__edit__actions">
        <%= form.submit '更新', class: :form__btn %>
      </div>  
    </div>
    <% end %>
  </div>
</div>
<%= render partial: 'top/footer' %>

app/views/coordinates/history.html.erb
<header>
  <div class ="pcHeader">
    <div class="pcHeader__headerInner">
      <div class="pcHeader__headerInner__mainHeader">
        <div class="pcHeader__headerInner__mainHeader__title">
          <%= link_to "Fashion Book", '/', class: "pcHeader__headerInner__mainHeader__title__main" %>
          <div class="pcHeader__headerInner__mainHeader__title__sub">毎日の服選びをおしゃれで楽に</div>
        </div>
      </div>
    </div>
  </div>
</header>
<% breadcrumb :history %>
<%= breadcrumbs separator: " &rsaquo; " %>
<div class="contents">
  <div class="content">
    <div class="content__mypage">
      <div class="content__mypage__left">
        <ul class="content__mypage__left__side">
          <li class="content__mypage__left__side__list">
            <%= link_to 'マイページ', user_path(current_user.id), class: "content__mypage__left__side__list__menu" %>
            <ul>
              <li>
                <%= link_to '#', class: "content__mypage__left__side__list__menu__tag" do %>
                  コーディネート選択<%= fa_icon("angle-right") %>
                <% end %>
              </li>
              <li>
                <%= link_to coordinates_path, class: "content__mypage__left__side__list__menu__tag" do %>
                  コーディネート一覧<%= fa_icon("angle-right") %>
                <% end %>
              </li>
              <li>
                <%= link_to coordinate_bookmarks_path(@coordinate), class: "content__mypage__left__side__list__menu__tag" do %>
                  お気に入り一覧<%= fa_icon("angle-right") %>
                <% end %>
              </li>
              <li>
                <%= link_to items_path, class: "content__mypage__left__side__list__menu__tag" do %>
                  アイテム一覧<%= fa_icon("angle-right") %>
                <% end %>
              </li>
              <li>
                <%= link_to history_coordinates_path, class: "content__mypage__left__side__list__menu__tag" do %>
                  閲覧履歴<%= fa_icon("angle-right") %>
                <% end %>
              </li>
            </ul>
          </li>
        </ul>
      </div>
      <div class="content__mypage__right">
        <div class="content__mypage__right__seach">
          <h2>閲覧履歴</h2>
        </div>
        <div class="content__mypage__right__history">
          <% if @histories.present? %>
            <% @histories.each do |history| %>
              <% if user_signed_in? && current_user.id == history.user_id %>
                <%= render partial: "coordinates/history", locals: { coordinate: @coordinate, coordinates: @coordinates, history: history } %>
              <% end %>
            <% end %>
          <% else %>
            <div class="content__mypage__right__history__no">コーディネートの閲覧履歴はありません</div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/coordinates/index.html.erb
<header>
  <div class ="pcHeader">
    <div class="pcHeader__headerInner">
      <div class="pcHeader__headerInner__mainHeader">
        <div class="pcHeader__headerInner__mainHeader__title">
          <%= link_to "Fashion Book", '/', class: "pcHeader__headerInner__mainHeader__title__main" %>
          <div class="pcHeader__headerInner__mainHeader__title__sub">毎日の服選びをおしゃれで楽に</div>
        </div>
      </div>
    </div>
  </div>
</header>
<% breadcrumb :index_coordinate %>
<%= breadcrumbs separator: " &rsaquo; " %>
<div class="contents">
  <div class="contents__coordinate">
    <div class="contents__coordinate__index">
      <div class="contents__coordinate__index__left">
        <ul class="contents__coordinate__index__left__side">
          <li class="contents__coordinate__index__left__side__list">
            <%= link_to 'マイページ', user_path(current_user.id), class: "contents__coordinate__index__left__side__list__menu" %>
            <ul>
              <li>
                <%= link_to coordinates_path, class: "contents__coordinate__index__left__side__list__menu__tag" do %>
                  コーディネート一覧<%= fa_icon("angle-right") %>
                <% end %>
              </li>
              <li>
                <%= link_to new_coordinate_path, class: "contents__coordinate__index__left__side__list__menu__tag" do %>
                  コーディネート登録<%= fa_icon("angle-right") %>
                <% end %>
              </li>
            </ul>
            <h2 class="contents__coordinate__index__left__side__list__menu">月</h2>
            <h2 class="contents__coordinate__index__left__side__list__menu">カラー</h2>
          </li>
        </ul>
      </div>
      <div class="contents__coordinate__index__right">
        <div class="contents__coordinate__index__right__seach">
          <h2>コーディネート一覧</h2>
        </div>
        <div class="contents__coordinate__index__right__list">
          <% @coordinates.each do |coordinate| %>
            <% if user_signed_in? && current_user.id == coordinate.user_id %>
              <%= render partial: "coordinate", locals: { coordinate: @coordinate, coordinate: coordinate } %>
            <% end %>
          <% end %>
          <%= paginate(@coordinates) %>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render partial: 'top/footer' %>

app/views/coordinates/new.html.erb
<header>
  <div class ="header">
    <div class="header__item">
      <div class="header__item__show">
        <div class="header__item__show__title">
          <%= link_to "Fashion Book", '/', class: "header__item__show__title__main" %>
          <div class="header__item__show__title__sub">毎日の服選びをおしゃれで楽に</div>
        </div>
      </div>
    </div>
  </div>
</header>
<% breadcrumb :new_coordinate %>
<%= breadcrumbs separator: " &rsaquo; " %>
<div class="contents">
  <div class="contents__coordinate">
    <div class="contents__coordinate__title">
      <h2>コーディネート登録</h2>
    </div>
    <div class="contents__coordinate__new">
    <%= form_with(model: @coordinate, class: :form, local: true) do |form| %>
      <% if @coordinate.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@coordinate.errors.count, "件のエラーにより") %> この投稿は保存できませんでした。</h2>
          <ul>
            <% @coordinate.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    
      <div class="contents__coordinate__new__image">
        <%= form.label :image, 'コーディネート画像' %>
        <%= form.file_field :image, class: :contents__coordinate__new__image__select, id: "image-form" %>
        <div id="file"></div>
      </div>

      <div class="contents__coordinate__new__name">
        <%= form.label :name, 'コーディネート名' %>
        <%= form.text_area :name, placeholder: :コーディネート名50文字まで, class: :form__name2 %>
      </div>

      <div class="contents__coordinate__new__introduction">
        <%= form.label :introduction, 'コーディネート詳細' %>
        <%= form.text_area :introduction, placeholder: :'コーディネート紹介文(2000文字以内)', class: 'form__introduction2 js-text' %>
        <P class="js_text_count"></P>
      </div>

      <div class="contents__coordinate__new__gender">
        <%= form.label :gender_id, '性別' %>
        <%= form.collection_select :gender_id, Gender.all, :id, :name, {prompt: "選択してください"}, {class: "form__gender"} %>
      </div>

      <div class="contents__coordinate__new__height">
        <%= form.label :height_id, '身長' %>
        <%= form.collection_select :height_id, Height.all, :id, :name, {prompt: "選択してください"}, {class: "form__height"} %>
      </div>

      <div class="contents__coordinate__new__age">
        <%= form.label :age_id, '年齢' %>
        <%= form.collection_select :age_id, Age.all, :id, :name, {prompt: "選択してください"}, {class: "form__age"} %>
      </div>

      <div class="contents__coordinate__new__month">
        <%= form.label :month_id, '投稿月' %>
        <%= form.collection_select :month_id, Month.all, :id, :name, {prompt: "選択してください"}, {class: "form__month"} %>
      </div>

      <div class="contents__coordinate__new__hairstyle">
        <%= form.label :hairstyle_id, '髪型' %>
        <%= form.collection_select :hairstyle_id, Hairstyle.all, :id, :name, {prompt: "選択してください"}, {class: "form__hairstyle"} %>
      </div>

      <div class="contents__coordinate__new__actions">
        <%= form.submit '投稿', class: :form__btn %>
      </div>  
    </div>
    <% end %>
  </div>
</div>
<%= render partial: 'top/footer' %>

app/views/coordinates/show.html.erb
<header>
  <div class ="header">
    <div class="header__item">
      <div class="header__item__show">
        <div class="header__item__show__title">
          <%= link_to "Fashion Book", '/', class: "header__item__show__title__main" %>
          <div class="header__item__show__title__sub">毎日の服選びをおしゃれで楽に</div>
        </div>
        <div class = "header__item__show__lists">
          <% if user_signed_in? && current_user.id == @coordinate.user_id %>
            <div class="header__item__show__lists__list">
              <%= link_to "編集", edit_coordinate_path(@coordinate.id), class: "header__item__show__lists__list__edit" %>
              <%= link_to "削除", coordinate_path(@coordinate.id), method: :delete, data: { confirm: '本当に削除しますか?' }, class: "header__item__show__lists__list__delete" %>
              <%= link_to '戻る', coordinates_path(@coordinate.id), class: "header__item__show__lists__list__back" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</header>
<% breadcrumb :show_coordinate %>
<%= breadcrumbs separator: " &rsaquo; " %>
<div class="contents">
  <div class="contents__coordinate">
    <div class="contents__coordinate__show">
      <div class="contents__coordinate__show__left">
        <div class="contents__coordinate__show__left__image">
          <% if @coordinate.image.present? %>
            <%= image_tag "#{@coordinate.image }", height: '100%', width: '95%' %>
          <% else %>
            <%= image_tag "/Unknown.png", height: '100%', width: '95%' %>
          <% end %>
        </div>
        <div class="contents__coordinate__show__left__like">
          <%= render partial: 'bookmarks/bookmark', locals: { post: @coordinate, posts: @coordinates, bookmarks: @bookmarks, bookmark: @bookmark } %> 
          <%= render partial: 'likes/like', locals: { post: @coordinate, posts: @coordinates, likes: @likes, like: @like } %> 
        </div>
        <div class="comment">
          <ul>
            <li class="comment__create">
              <h3 class="comment__create__nickname"><%= @coordinate.user.nickname %>さんへのコメント</h3>
            </li>
            <div id="comments_area", class="comment__area">
              <%= render partial: 'comments/index', locals: { comments: @comments } %>
            </div>
          </ul>
          <% if user_signed_in? %>
            <div class="comment__create">
              <div class="comment__create__text">
                <%= render partial: 'comments/form', locals: { comment: @comment, coordinate: @coordinate } %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div class="contents__coordinate__show__right">
        <div class="contents__coordinate__show__right__top">
          <div class="contents__coordinate__show__right__top__name">
            <span>【コーディネート】</span><br>
            <%= @coordinate.name %>
          </div>
          <div class="contents__coordinate__show__right__top__model">
            <span>モデル情報:</span><br>
            <div class="contents__coordinate__show__right__top__model__height">
              <%= @coordinate.height.name %> /
            </div>
            <div class="contents__coordinate__show__right__top__model__gender">
              <%= @coordinate.gender.name %> /
            </div>
            <div class="contents__coordinate__show__right__top__model__hairstyle">
              <%= @coordinate.hairstyle.name %>
            </div>
          </div>
        </div>
        <div class="contents__coordinate__show__right__low">
          <div class="contents__coordinate__show__right__low__introduction">
          <span>【コーディネート詳細】</span>
          <%= @coordinate.introduction %>
          </div>
          <div class="contents__coordinate__show__right__low__time">
            <%= @coordinate.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render partial: 'top/footer' %>