config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root 'top#index'

  resources :address, only: [:show, :edit, :update, :destroy]
  resources :users, only: [:show, :edit, :update, :destroy] do
    collection do
      get 'profile', to: 'users#profile'
      get 'overview', to: 'users#overview'
      get 'problem', to: 'users#problem'
    end
  end

  resources :items, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'season', to: 'items#season'
      get 'color', to: 'items#color'
      get 'brand', to: 'items#brand'
    end
    collection do # 新規用（new) usr:items/newのため
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
      get 'category_size', defaults: { format: 'json' }
    end
    member do # 編集(edit用) usl: items/id/editのため
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
      get 'category_size', defaults: { format: 'json' }
    end
    resources :categories, only: [:show]
  end
  
  resources :coordinates do
    collection do
      get 'history', to: 'coordinates#history'
    end
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resources :bookmarks, only: [:index, :create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :address
  
  has_many :items, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :coordinates, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_coordinates, through: :likes, source: :coordinate
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_coordinates, through: :bookmarks, source: :coordinate

  has_many :browsing_histories, dependent: :destroy

  validates :nickname, :birth_date, :sex, presence: true
  validates :nickname, presence: true, length: { minimum: 1 ,maximum:20  }
  validates :password, presence: true, length: { minimum: 6 ,maximum:128 }
  validates :email, presence: true, format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },uniqueness: true
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @user = User.new
    @results = Address.where('prefecture_id IN(?)', params[:prefecture_id])
    super
  end

  # POST /resource
  def create
    @user = User.new(sign_up_params)
    unless @user.valid?
      flash.now[:alert] = @user.errors.full_messages
      render :new and return
    end
    session["devise.regist_data"] = {user: @user.attributes}
    session["devise.regist_data"][:user]["password"] = params[:user][:password]
    @address = @user.build_address
    render :new_address
  end

  def create_address
    @user = User.new(session["devise.regist_data"]["user"])
    @address = Address.new(address_params)
    unless @address.valid?
      flash.now[:alert] = @address.errors.full_messages
      render :new_address and return
    end
    @user.build_address(@address.attributes)
    @user.save
    session["devise.regist_data"]["user"].clear
    sign_in(:user, @user)
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  def address_params
    params.require(:address).permit(:family_name,:first_name,:family_name_kana,:first_name_kana,:prefecture_id,:zip_code,:municipality,:address)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]

  def show
    @user = User.find(params[:id])
    @parents = Category.where(ancestry: nil)
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email,:birth_date)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="content__user">
  <div class="content__user__top">
    <%# <% breadcrumb :sign_in %>
    <%# <%= breadcrumbs separator: " &rsaquo; " %>
  </div>
  <div class="content__user__body">
    <div class="content__user__body__left">
      <h2>住所情報変更</h2>
    </div>

    <div class="content__user__body__right">
      <%= form_for(@address, as: @address, url: addresses_path(@address), html: { method: :put }) do |f| %>
        <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "件のエラーにより") %> 保存できませんでした。</h2>

            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="field">
          <%# <%= render "devise/shared/error_messages", resource: @address %>

          <div class="field__name">
            <%= f.label :姓名（漢字 %>
            <%= f.text_field :family_name, placeholder: "漢字姓", class: "field__name__family" %>
            <%= f.text_field :first_name, placeholder: "漢字名", class: "field__name__first" %>
          </div>

          <div class="field__kana">
            <%= f.label :姓名（カナ） %>
            <%= f.text_field :family_name_kana, placeholder: "カナ姓", class: "field__kana__family" %>
            <%= f.text_field :first_name_kana, placeholder: "カナ名", class: "field__kana__first" %>
          </div>

          <div class="field__prefecture">
            <%= f.label :prefecture_id, "都道府県" %>
            <%= f.collection_select :prefecture_id, Prefecture.all, :id, :name, prompt: "", class: "field__prefecture__select-box" %>
          </div>

          <div class="field__zipcode">
            <%= f.label :zip_code %><br />
            <%= f.text_field :zip_code, placeholder: "郵便番号" %>
          </div>

          <div class="field__municipality">
            <%= f.label :municipality %><br />
            <%= f.text_field :municipality, placeholder: "市区町村" %>
          </div>

          <div class="field__address">
            <%= f.label :address %><br />
            <%= f.text_field :address, placeholder: "番地" %>
          </div>

          <div class="actions">
            <%= f.submit "更新" %>
          </div>
        </div>
      <% end %>
      <div class="session">
        <%# <%= render "devise/shared/links" %>
      </div>
    </div>
  </div>
</div>

app/views/users/overview.html.erb
<header>
  <div class ="pcHeader">
    <div class="pcHeader__headerInner">
      <div class="pcHeader__headerInner__mainHeader">
        <div class="pcHeader__headerInner__mainHeader__title">
          <%= link_to "Fashion Book", '/', class: "pcHeader__headerInner__mainHeader__title__main" %>
          <div class="pcHeader__headerInner__mainHeader__title__sub">毎日の服選びをおしゃれで楽に</div>
        </div>
      </div>
    </div>
  </div>
</header>
<div class="content">
  <div class="content__overview">
    <div class="content__overview__left">
      <h2> 制作概要 </h2>
      <div class="content__overview__left__category">
        <div class="content__overview__left__category__time">
        【更新日時】2020/7/10現在
        </div>
      </div>
      <%= link_to "戻る", :back, class: "content__overview__left__back" %>
    </div>

    <div class="content__overview__right">
      <div class="content__overview__right__list">
        【目的】<br/>
        ・服装を考えずに選択することができる<br>
        ・朝の時間短縮<br>
        ・衣服の管理<br>
        ・衣服購入の参考、時間短縮<br>
        <br>
        【作成理由】<br />
        ・フリマアプリ以外で複雑なアプリを作成したいと思ったから<br>
        ・実用的なアプリを作成したいと考えたから<br>
        <br />
        【このさきやってみたいこと】<br/>
        Web系エンジニアとして働きたいと考えております。
        未経験からプログラミングスクールに通ったので簡単なWebデザイン、フロントエンド系の業務をこなすことは可能です。
        現時点で興味関心が強いのはサーバーサイド系ですが、未経験から学習しているため経験が少なく、実装できることも少ないため（JavaScript・jQueryなど）スクールで学習し、学びが不足している分野を日々、学習しています。<br/>
        今後もこれまで経験したことのない技術や業務のシステムに挑戦していきたい！
        何年経っても成長できる要素はあると学生時代の経験から学んだので日々の積み上げを大切にしてクライアントのニーズに答えれるようなサービスを制作していきたい。
        そのため基本的には、ITを活用して世の中の人々の役に立つものを作るというスタンスが達成できれば良いので言語などには囚われてなく必要であればどの言語でも学ぶ意欲があります。<br />
        <br>
      </div>
    </div>
  </div>
</div>
<%= render partial: 'top/footer' %>

app/views/users/problem.html.erb
<header>
  <div class ="pcHeader">
    <div class="pcHeader__headerInner">
      <div class="pcHeader__headerInner__mainHeader">
        <div class="pcHeader__headerInner__mainHeader__title">
          <%= link_to "Fashion Book", '/', class: "pcHeader__headerInner__mainHeader__title__main" %>
          <div class="pcHeader__headerInner__mainHeader__title__sub">毎日の服選びをおしゃれで楽に</div>
        </div>
      </div>
    </div>
  </div>
</header>
<div class="content">
  <div class="content__problem">
    <div class="content__problem__left">
      <h2> 実装機能・課題 </h2>
      <div class="content__problem__left__list">
      【更新日時】2020/7/10現在<br>
      </div>
      <%= link_to "戻る", :back, class: "content__problem__left__back" %>
    </div>

    <div class="content__problem__right">
      <div class="content__problem__right__list">
        【実装機能】<br>
        <必須><br>
        ・管理ユーザ登録・編集・削除機能、管理ユーザログイン機能<br>
        ・住所変更、メールパスワード変更、ログアウト機能<br>
        ・アイテム登録・編集・削除機能<br>
        ・コーディネーション登録・編集・削除機能<br>
        ・カテゴリ機能（３階層）、文字数カウント機能、お気に入り機能<br>
        ・画像アップロード表示、非同期コメント機能、非同期いいね機能<br>
        ・もっと見る機能(投稿部分)、もっと見る機能(コメント部分)<br>
        ・パンくず機能、ページネーション機能<br>
        <br>
        <br>
        【未実行】<br>
          ・単体テスト、機能テスト、統合テスト<br>
          ・公開・非公開機能、検索機能、ランキング機能<br>
          ・ランダム機能（画像）、slick導入でスライド<br>
        <br>
        <br>
        【課題】<br/>
          ・コメント非同期崩れ<br>
          <span>理由：コメントした際に崩れる</span><br>
          ・アイテム部分で非同期でサイズを選択<br>
          <span>理由：カテゴリによってサイズが変わる方が使いやすい為</span><br>
          ・編集での画像・カテゴリ部分の問題を解消<br>
          <span>理由：viewで表示されていない為</span><br>
          ・カラム表示ごとにview作成<br>
          <span>理由：要素ごとに表示することで探しやすくする</span><br>
          ・コーディネートでアイテム取得<br>
          <span>理由：コーディネートでどのようなアイテムを使用しているか明確にする為</span><br>
        <br>
        <br>
      </div>
    </div>
  </div>
</div>
<%= render partial: 'top/footer' %>

app/views/users/profile.html.erb
<header>
  <div class ="pcHeader">
    <div class="pcHeader__headerInner">
      <div class="pcHeader__headerInner__mainHeader">
        <div class="pcHeader__headerInner__mainHeader__title">
          <%= link_to "Fashion Book", '/', class: "pcHeader__headerInner__mainHeader__title__main" %>
          <div class="pcHeader__headerInner__mainHeader__title__sub">毎日の服選びをおしゃれで楽に</div>
        </div>
      </div>
    </div>
  </div>
</header>
<div class="content">
  <div class="content__profile">
    <div class="content__profile__left">
      <h2> 作成者概要 </h2>
      <img src="/line_743968890967290.jpg", class="content__profile__left__image">
      <div class="content__profile__left__field">
        <%= form_with html: { method: :put } do |f| %>
          <div class="field">

            <div class="field__nickname">
              <%= f.label :nickname, '名前' %>
              : 植田孝啓（うえだたかひろ）
            </div>
          
            <div class="field__age">
              <%= f.label :age, '年齢' %>
              : 1996/04/25　(24歳)
            </div>

            <div class="field__sex">
              <%= f.label :sex, '性別' %>
              : 男性
            </div>

            <div class="field__prefecture">
              <%= f.label :prefecture, '都道府県' %>
              : 大阪府
            </div>
            
          </div>
        <% end %>
      </div>
      <%= link_to "戻る", :back, class: "content__profile__left__back" %>
    </div>

    <div class="content__profile__right">
      <div class="content__profile__right__list">
      <%= form_with html: { method: :put } do |f| %>
        <%= f.label :profile, '自己紹介' %><br />
          前職は大阪の信用金庫で2月から未経験でテックキャンプに通っている駆け出しエンジニアです！<br />
          テックキャンプではHTML&CSS,Ruby,Ruby on Railsを中心に学びました。<br />
          現在は独自のアプリ開発とC言語の学習（翌々はJava,PHPも学習予定）<br>
          <br />
          【今やっていること】<br/>
          ・転職サイトを活用して企業勉強（業務内容は？職場環境は？）<br />
          ・就職活動、少しでも知識アップのため学習<br />
          ・スクールで学習した言語を活用してアプリ・ホームページ開発<br />
          <br />
          【テックキャンプでの学習経験】<br />
          ・HTML・CSS・Ruby・Ruby on Rails・JavaScript・jQuery・SQL・Git・ GitHub
          Haml・SCSS・AWS　等の技術を用いたアプリケーション開発<br />
          ・共同開発の経験（テックキャンプでのチーム開発）<br />
          ・各種プログラミング言語の基礎知識の強化（テックキャンプ・progate,書籍など）<br/>
          <br>
          アプリに関する今後行いたいこと→<%= link_to "制作概要へ", overview_users_path %><br>
          <br />
          【学生時代に打ち込んだこと】<br/>
          中学校から陸上競技を始め、陸上競技で全国大会出場を目標に掲げて練習に取り組んでいました。結果は大学３年生のときに悲願の全国大会出場を達成しました。その要因は練習効率を高めるために練習の距離やタイムだけでなく、疲労度と強度も数値化してグラフ化する取り組みを行ったことだと思います。<br/>
          グラフの内容は疲労度と練習強度に関しては私の感覚や練習状況を踏まえて10段階に分けて考え折れ線グラフで表示。練習距離は縦線グラフで表示することで具体的に可視化することができ、大会に向けての調整や練習メニューを立てる参考になりました。<br/>
          グラフを作成するようになってからタイムでいいますと10キロで2分短縮することができ、怪我のリスクが軽減されました。
          目標を設定し、達成するために自分に何が足らなくてどうしたら良いのかを考え実行する力、失敗をしながら努力し続けることが重要だと経験から学びました！
        </div>
      <% end %>
    </div>
  </div>
</div>
<%= render partial: 'top/footer' %>

app/views/users/show.html.erb
<header>
  <div class ="pcHeader">
    <div class="pcHeader__headerInner">
      <div class="pcHeader__headerInner__mainHeader">
        <div class="pcHeader__headerInner__mainHeader__title">
          <%= link_to "Fashion Book", '/', class: "pcHeader__headerInner__mainHeader__title__main" %>
          <div class="pcHeader__headerInner__mainHeader__title__sub">毎日の服選びをおしゃれで楽に</div>
        </div>
        <%# %a(href="/")
          = image_tag 'logo.png', height: '40px', width: '150px', alt: 'icon', class: 'pcHeader__headerInner__mainHeader__app'
        .pcHeader__headerInner__mainHeader__searchBox
          = text_field_tag '', '', placeholder: 'キーワードから探す', class: 'pcHeader__headerInner__mainHeader__searchBox__box'
          .pcHeader__headerInner__mainHeader__searchBox__btn
            %a(href="#")
              = image_tag 'icon-search 1.png', height: '100%', width: '100%', alt: 'search' %>
      </div>
      <div class="pcHeader__headerInner__nav">
        <ul class = "pcHeader__headerInner__nav__listLeft">
          <li class = "pcHeader__headerInner__nav__listLeft__first">
            <%= link_to "#" do %> 
              カテゴリー
            <% end%>
            <ul class = "pcHeader__headerInner__nav__listLeft__first__parents">
              <% @parents.each do |parent| %> 
              <%# 親カテゴリの中身 %>
                <li class = "pcHeader__headerInner__nav__listLeft__first__parents__parent">
                  <%= link_to "#" do%> 
                    <%= parent.name %> 
                  <% end %>
                  <%# 子カテゴリの大枠 %>
                  <ul class = "pcHeader__headerInner__nav__listLeft__first__parents__parent__children">
                    <% parent.children.each do |child| %> 
                      <%# 子カテゴリの中身 %>
                      <li class = "pcHeader__headerInner__nav__listLeft__first__parents__parent__children__child">
                        <%= link_to "#" do %> 
                          <%= child.name %> 
                        <% end %>
                        <%# 孫カテゴリの大枠 %>
                        <ul class = "pcHeader__headerInner__nav__listLeft__first__parents__parent__children__child__grandchildren">
                          <% child.children.each do |grandchild| %> 
                            <%# 孫カテゴリの中身 %>
                            <li class = "pcHeader__headerInner__nav__listLeft__first__parents__parent__children__child__grandchildren__grandchild">
                              <%= link_to "#" do %> 
                                <%= grandchild.name %> 
                              <% end %>
                            </li>
                          <% end %>
                        </ul>
                      </li>
                    <% end %>
                  </ul>
                </li>
              <% end %>
            </ul>
          </li>
        </ul>
        <%= link_to "ブランド", '#', class:"pcHeader__headerInner__nav__listLeft__item" %>
        <div class = "pcHeader__headerInner__nav__listRight">
          <% if user_signed_in? %>
            <%= link_to "マイページ", user_path(current_user.id), class:"pcHeader__headerInner__nav__listRight"%>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "ログイン", new_user_session_path, class:"pcHeader__headerInner__nav__listLeft__first" %>
            <%= link_to "新規会員登録", new_user_registration_path, class:"pcHeader__headerInner__nav__listLeft__item" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</header>
<% breadcrumb :user %>
<%= breadcrumbs separator: " &rsaquo; " %>
<div class="contents">
  <div class="content">
    <div class="content__mypage">
      <div class="content__mypage__left">
        <ul class="content__mypage__left__side">
          <li class="content__mypage__left__side__list">
            <h2 class="content__mypage__left__side__list__menu">マイページ</h2>
            <ul>
              <li>
                <%= link_to '#', class: "content__mypage__left__side__list__menu__tag" do %>
                  コーディネート選択<%= fa_icon("angle-right") %>
                <% end %>
              </li>
              <li>
                <%= link_to coordinates_path, class: "content__mypage__left__side__list__menu__tag" do %>
                  コーディネート一覧<%= fa_icon("angle-right") %>
                <% end %>
              </li>
              <li>
                <%= link_to coordinate_bookmarks_path(@user.coordinates), method: :get, class: "content__mypage__left__side__list__menu__tag" do %>
                  お気に入り一覧<%= fa_icon("angle-right") %>
                <% end %>
              </li>
              <li>
                <%= link_to items_path, class: "content__mypage__left__side__list__menu__tag" do %>
                  アイテム一覧<%= fa_icon("angle-right") %>
                <% end %>
              </li>
              <li>
                <%= link_to history_coordinates_path, class: "content__mypage__left__side__list__menu__tag" do %>
                  閲覧履歴<%= fa_icon("angle-right") %>
                <% end %>
              </li>
            </ul>
            <h2 class="content__mypage__left__side__list__menu">設定</h2>
            <ul>
              <li>
                <%= link_to address_path, class: "content__mypage__left__side__list__menu__tag" do %>
                  プロフィール<%= fa_icon("angle-right") %>
                <% end %>
              </li>
              <li>
                <%= link_to edit_address_path, class: "content__mypage__left__side__list__menu__tag" do %>
                  住所変更<%= fa_icon("angle-right") %>
                <% end %>
              </li>
              <li>
                <%= link_to edit_user_registration_path, class: "content__mypage__left__side__list__menu__tag" do %>
                  メール・パスワード変更<%= fa_icon("angle-right") %>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete, class: "content__mypage__left__side__list__menu__tag" do %>
                  ログアウト<%= fa_icon("angle-right") %>
                <% end %>
              </li>
            </ul>
            <h2 class="content__mypage__left__side__list__menu">退会</h2>
            <ul>
              <li>
                <%# <%= link_to user_path(@user.id), method: :delete, data: { confirm: '本当に削除しますか?' }, class: "content__mypage__left__side__list__menu__tag" do %>
                  <%# 退会<%= fa_icon("angle-right") %>
                <%# <% end %>
              </li>
            </ul>
          </li>
        </ul>
      </div>
      <div class="content__mypage__right">
        <div class="content__mypage__right__seach">
        <h2>マイページ</h2>
        </div>
      </div>
    </div>
  </div>
</div>